[project]

site_name = "Dessert's Guide"
site_description = "A comprehensive guide for the game Brickadia"
site_author = "DessertSource"
site_url = "https://dessertsource.github.io/dessert-brickadia-guide"

copyright = "Copyright &copy; 2025 DessertSource"

nav = [
    { "Home" = [
        "Home/index.md"
    ]},

    { "Wires" = [
        "Wires/index.md",
        { "Operations" = [
            "Wires/Operations/index.md",
            { "Conditional" = "Wires/Operations/Conditional.md" },
            { "Logic" = "Wires/Operations/Logic.md" },
            { "Math" = "Wires/Operations/Math.md" },
            { "Bitwise" = "Wires/Operations/Bitwise.md" },
            { "Control Flow" = "Wires/Operations/Control_Flow.md" }
        ]},
        { "Variables" = [
            "Wires/Variables/index.md",
            { "Adding & getting variables" = "Wires/Variables/Adding.md" },
            { "Modifying variables" = "Wires/Variables/Modifying.md" }
        ]},
        { "Entities" = [
            "Wires/Entities/index.md",
            { "Brick Grids" = "Wires/Entities/Brick_Grids.md" }
        ]},
    ]},

    { "Glossary" = [
        "Glossary/index.md",
        { "Entities" = "Glossary/Entities.md" },
        { "Value Types" = "Glossary/Value_Types.md" },
        { "Permissions" = "Glossary/Permissions.md" },
        { "Chat Commands" = "Glossary/Chat_Commands.md" }        
    ]}
]

extra_css = ["assets/stylesheets/extra.css"]

extra_javascript = [
    "assets/javascripts/mathjax.js",
    "assets/javascripts/tablesort.js",
    "https://unpkg.com/mathjax@4/tex-mml-chtml.js",
    "https://unpkg.com/tablesort@5/dist/tablesort.min.js"
]

[project.theme]

variant = "modern"

logo = "assets/logo.svg"
favicon = "assets/favicon.svg"

language = "en"

features = [
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tooltips",

    "navigation.expand",
    "navigation.footer",
    "navigation.indexes",
    "navigation.path",
    "navigation.tabs",
    "navigation.top",
    "navigation.tracking",

    "search.highlight",

    "toc.follow"
]

[project.plugins.offline]
enabled = true

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.theme.font]
text = "Inter"
code = "Roboto Mono"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/DessertSource/dessert-brickadia-guide"